#pragma once

#define ETL_CPP11_SUPPORTED 1
#define ETL_USING_STL 1
#define ETL_NOT_USING_STLPORT 1
#define ETL_FORCE_STD_INITIALIZER_LIST 1

#ifdef ETL_FORCE_ETL_INITIALIZER_LIST
#undef ETL_FORCE_ETL_INITIALIZER_LIST
#endif
#ifdef ETL_NO_INITIALIZER_LIST
#undef ETL_NO_INITIALIZER_LIST
#endif
